### ISSUE TITLE
Model Checkpointing Causes Cuda OOM

### ISSUE THREAD

**Issue by profPlum** [Lightning-AI/pytorch-lightning#20312]
### Bug description

I'm using FSDP and model checkpointing (default settings for both). My model has a lot of parameters (not sure exactly how much), enough so that it probably can't all fit on one GPU. But it seems that the default setting for model checkpointing with FSDP is to collate all of the parameters onto the rank 0 GPU?? Because it causes OOM after a full successful epoch; I tested it by disabling model checkpointing and I found that the memory error went away.

I think that we are all juicing our GPUs for as much performance as is possible. So collating the parameters on the the rank 0 GPU just doesn't make sense. Obviously the correct way to do this is to collate the parameters on the CPU then save the file.

### What version are you seeing the problem on?

v2.3

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.4.0):
#- PyTorch Version (e.g., 2.4):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

**Comment by fclearner** [comment]
Is this problem solved? I have just met the same one, maybe its related to the ckpt-save part

**Comment by bhimrazy** [comment]
Could this be related to #19674 ? will look into it.
